// This file was generated by counterfeiter
package fakes

import (
	"io"
	"sync"

	"github.com/svett/nuvi"
)

type FakeExtractor struct {
	ExtractStub        func(reader io.Reader) []string
	extractMutex       sync.RWMutex
	extractArgsForCall []struct {
		reader io.Reader
	}
	extractReturns struct {
		result1 []string
	}
}

func (fake *FakeExtractor) Extract(reader io.Reader) []string {
	fake.extractMutex.Lock()
	fake.extractArgsForCall = append(fake.extractArgsForCall, struct {
		reader io.Reader
	}{reader})
	fake.extractMutex.Unlock()
	if fake.ExtractStub != nil {
		return fake.ExtractStub(reader)
	} else {
		return fake.extractReturns.result1
	}
}

func (fake *FakeExtractor) ExtractCallCount() int {
	fake.extractMutex.RLock()
	defer fake.extractMutex.RUnlock()
	return len(fake.extractArgsForCall)
}

func (fake *FakeExtractor) ExtractArgsForCall(i int) io.Reader {
	fake.extractMutex.RLock()
	defer fake.extractMutex.RUnlock()
	return fake.extractArgsForCall[i].reader
}

func (fake *FakeExtractor) ExtractReturns(result1 []string) {
	fake.ExtractStub = nil
	fake.extractReturns = struct {
		result1 []string
	}{result1}
}

var _ nuvi.Extractor = new(FakeExtractor)
