// This file was generated by counterfeiter
package fakes

import (
	"io"
	"sync"

	"github.com/svett/nuvi"
)

type FakeArchiveWalker struct {
	WalkStub        func(reader io.Reader, walker nuvi.ArchiveWalkerFunc)
	walkMutex       sync.RWMutex
	walkArgsForCall []struct {
		reader io.Reader
		walker nuvi.ArchiveWalkerFunc
	}
}

func (fake *FakeArchiveWalker) Walk(reader io.Reader, walker nuvi.ArchiveWalkerFunc) {
	fake.walkMutex.Lock()
	fake.walkArgsForCall = append(fake.walkArgsForCall, struct {
		reader io.Reader
		walker nuvi.ArchiveWalkerFunc
	}{reader, walker})
	fake.walkMutex.Unlock()
	if fake.WalkStub != nil {
		fake.WalkStub(reader, walker)
	}
}

func (fake *FakeArchiveWalker) WalkCallCount() int {
	fake.walkMutex.RLock()
	defer fake.walkMutex.RUnlock()
	return len(fake.walkArgsForCall)
}

func (fake *FakeArchiveWalker) WalkArgsForCall(i int) (io.Reader, nuvi.ArchiveWalkerFunc) {
	fake.walkMutex.RLock()
	defer fake.walkMutex.RUnlock()
	return fake.walkArgsForCall[i].reader, fake.walkArgsForCall[i].walker
}

var _ nuvi.ArchiveWalker = new(FakeArchiveWalker)
