// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"gopkg.in/redis.v4"

	"github.com/svett/nuvi"
)

type FakeRedisClient struct {
	LPushStub        func(key string, values ...interface{}) *redis.IntCmd
	lPushMutex       sync.RWMutex
	lPushArgsForCall []struct {
		key    string
		values []interface{}
	}
	lPushReturns struct {
		result1 *redis.IntCmd
	}
	LRangeStub        func(key string, start, stop int64) *redis.StringSliceCmd
	lRangeMutex       sync.RWMutex
	lRangeArgsForCall []struct {
		key   string
		start int64
		stop  int64
	}
	lRangeReturns struct {
		result1 *redis.StringSliceCmd
	}
}

func (fake *FakeRedisClient) LPush(key string, values ...interface{}) *redis.IntCmd {
	fake.lPushMutex.Lock()
	fake.lPushArgsForCall = append(fake.lPushArgsForCall, struct {
		key    string
		values []interface{}
	}{key, values})
	fake.lPushMutex.Unlock()
	if fake.LPushStub != nil {
		return fake.LPushStub(key, values...)
	} else {
		return fake.lPushReturns.result1
	}
}

func (fake *FakeRedisClient) LPushCallCount() int {
	fake.lPushMutex.RLock()
	defer fake.lPushMutex.RUnlock()
	return len(fake.lPushArgsForCall)
}

func (fake *FakeRedisClient) LPushArgsForCall(i int) (string, []interface{}) {
	fake.lPushMutex.RLock()
	defer fake.lPushMutex.RUnlock()
	return fake.lPushArgsForCall[i].key, fake.lPushArgsForCall[i].values
}

func (fake *FakeRedisClient) LPushReturns(result1 *redis.IntCmd) {
	fake.LPushStub = nil
	fake.lPushReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) LRange(key string, start int64, stop int64) *redis.StringSliceCmd {
	fake.lRangeMutex.Lock()
	fake.lRangeArgsForCall = append(fake.lRangeArgsForCall, struct {
		key   string
		start int64
		stop  int64
	}{key, start, stop})
	fake.lRangeMutex.Unlock()
	if fake.LRangeStub != nil {
		return fake.LRangeStub(key, start, stop)
	} else {
		return fake.lRangeReturns.result1
	}
}

func (fake *FakeRedisClient) LRangeCallCount() int {
	fake.lRangeMutex.RLock()
	defer fake.lRangeMutex.RUnlock()
	return len(fake.lRangeArgsForCall)
}

func (fake *FakeRedisClient) LRangeArgsForCall(i int) (string, int64, int64) {
	fake.lRangeMutex.RLock()
	defer fake.lRangeMutex.RUnlock()
	return fake.lRangeArgsForCall[i].key, fake.lRangeArgsForCall[i].start, fake.lRangeArgsForCall[i].stop
}

func (fake *FakeRedisClient) LRangeReturns(result1 *redis.StringSliceCmd) {
	fake.LRangeStub = nil
	fake.lRangeReturns = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

var _ nuvi.RedisClient = new(FakeRedisClient)
