// This file was generated by counterfeiter
package fakes

import (
	"io"
	"sync"

	"github.com/svett/nuvi"
)

type FakeCacher struct {
	CacheStub        func(reader io.Reader)
	cacheMutex       sync.RWMutex
	cacheArgsForCall []struct {
		reader io.Reader
	}
}

func (fake *FakeCacher) Cache(reader io.Reader) {
	fake.cacheMutex.Lock()
	fake.cacheArgsForCall = append(fake.cacheArgsForCall, struct {
		reader io.Reader
	}{reader})
	fake.cacheMutex.Unlock()
	if fake.CacheStub != nil {
		fake.CacheStub(reader)
	}
}

func (fake *FakeCacher) CacheCallCount() int {
	fake.cacheMutex.RLock()
	defer fake.cacheMutex.RUnlock()
	return len(fake.cacheArgsForCall)
}

func (fake *FakeCacher) CacheArgsForCall(i int) io.Reader {
	fake.cacheMutex.RLock()
	defer fake.cacheMutex.RUnlock()
	return fake.cacheArgsForCall[i].reader
}

var _ nuvi.Cacher = new(FakeCacher)
